### ISSUE TITLE
可以帮忙添加文章吗，谢谢啦~~

### ISSUE THREAD

**Issue by callmepony** [saveweb/review-2021#13]
修改总是无法提交，麻烦帮忙添加一下噢~~ 感谢
[人生浪费指南 | 2021年终总结 - 查令十字街 84 号](https://www.javis.me/post/ri-chang/ren-sheng-lang-fei-zhi-nan-%7C-2021nian-zhong-zong-jie)

**Comment by yzqzss** [comment]
> 麻烦帮忙添加一下噢~~ 感谢

已添加！
