### ISSUE TITLE
自荐 2021 总结

### ISSUE THREAD

**Issue by imba97** [saveweb/review-2021#36]
[《留下了遗憾的 2021》](https://imba97.cn/archives/750/)

**Comment by yzqzss** [comment]
抱歉，仓库没开通知，现在才处理。

**Comment by imba97** [comment]
3q，已经在写2022的总结了，争取每年参加

**Comment by yzqzss** [comment]
嗯， 2022 年的仓库也开了： saveweb/review-2022
